# -*- coding: utf-8 -*-
"""pratikum 08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gFWhJoBk07h5_OcofU-CnX0LNOqqwDE2

Praktikum 01 – Fungsi Dasar dengan def
"""

def sapa():
  print("halo,selamat datang di politeknik negeri semarang!")

sapa()

"""Praktikum 02 – Fungsi dengan Parameter dan Return

"""

def tambah(a,b):
  return(a+b)

hasil= tambah(7,3)
print("hasil penjumlahan", hasil)

"""Praktikum 03 – Fungsi dengan Default Argument"""

def sapa(nama="mahasiswa"):
  print("halo", nama )

sapa()
sapa("andi")

"""Praktikum 04 – Fungsi dengan *args dan **kwargs"""

def jumlahkan(*args):
  return sum(args)

def biodata(**kwargs):
  for key,value in kwargs.items():
    print(f"{key}:{value}")

print("total:", jumlahkan (1,2,3,4,5))
biodata (nama="budi", umur=20, prodi="TRK")

"""Praktikum 05 – Scope Variabel"""

x=10

def ubah():
  x=5
  print("bilangan lokal:", x)

ubah()
print("nilai global:", x )

"""Praktikum 06 – Fungsi Lambda"""

kali = lambda x, y : x * y
print('hasil perkalian', kali(5,3))

"""Praktikum 07 – Fungsi Decorator"""

def decorator_sapa(fungsi):
  def wrapper():
    print ("sebelum fungsi dijalankan....")
    fungsi()
    print("setelah fungsi dijalankan...")
  return wrapper

@decorator_sapa
def sapa():
  print("halo, mahasiswa polines!")

sapa ()

"""Praktikum 08 – Studi Kasus: Menghitung Rata-rata Nilai Mahasiswa"""

def hitung_rata(data):
  return sum(data) / len(data)

nilai=[80, 90, 85]
rata= hitung_rata(nilai)

print("rata-rata nilai:", rata)

"""Penugasan

Fungsi sederhana
"""

def perkenalan ():
  print(f"halo, nama saya {nama},saya dari {prodi}")

nama=input("masukkan nama:")
prodi=input("masukkan prodi anda:")
perkenalan()

"""Fungsi dengan parameter dan return"""

def luas_persegi(panjang,lebar):
  return (panjang * lebar)


hitung_luas_persegi = luas_persegi(7,3)
print(f"panjang persegi ialah: {hitung_luas_persegi}")

"""Fungsi dengan Default Argument"""

def salam(waktu="pagi", nama="mahasiswa"):
  print("selamat", waktu, nama, "!")

salam("pagi", "lia")

"""Fungsi dengan args"""

def total (*angka):
  return sum(angka)

print ("total", total(1,2,3))
print("total", total(1,2,3,4,5))
print ("total", total(1,2,3,4,5,6,7))

"""Fungsi dengan kwargs"""

def info_barang(**data):
  for key, value in data.items():
    print(f"{key}:{value}")

info_barang(nama="buku", harga=15000, stok=30)

"""Scope Variabel"""

x=100

def ubah():
  x=50
  print ("bilangan lokal", x)

ubah()
print("bilangan lokal", x)

"""Fungsi Lambda

A. lambda untuk menghitung kuadrat sebuah bilangan.
"""

kuadrat = lambda x: x**2

print(kuadrat(5))

"""lambda untuk menghitung keliling lingkaran"""

keliling_lingkaran= lambda r: 2*3.14*r

print(keliling_lingkaran(7))

"""Fungsi Decorator"""

def decorator_logger(fungsi):
  def wrapper():
    print("memulai fungsi...")
    fungsi()
    print("fungsi selesai dijalankan...")
  return wrapper()

@decorator_logger
def halo():
  print("halo semua")

"""Studi Kasus Nyata – Program Nilai"""

def input_nilai():
  nilai=[]
  jumlah= int(input("masukkan nilai:"))
  for i in range(jumlah):

# Input nilai ujian
def input_nilai_ujian():
    nilai_ujian = []
    print("Masukkan nilai ujian (ketik 'stop' untuk berhenti)")
    while True:
        n = input(f"Masukkan nilai ujian ke-{len(nilai_ujian)+1}: ")
        if n.lower() == "stop":
            break
        try:
            nilai_ujian.append(float(n))
        except ValueError:
            print("Input tidak valid, masukkan angka atau 'stop'.")
    return nilai_ujian

def rata_nilai(nilai_ujian):
  return sum(nilai_ujian)/len(nilai_ujian)

def status_kelulusan(rata_nilai):
    if rata_ujian > 59:
        return "Lulus"
    else:
        return "Tidak Lulus"

nilai_akhir = lambda tugas, rata_ujian: (0.4 * tugas) + (0.6 * rata_ujian)

nilai_ujian = input_nilai_ujian()
rata_ujian = rata_nilai(nilai_ujian)
tugas = float(input("Masukkan nilai tugas: "))

print("Rata-rata ujian:", rata_ujian)
print("Status kelulusan:", status_kelulusan(rata_ujian))
print("Nilai akhir:", nilai_akhir(tugas, rata_ujian))